name: Deploy Backend

on:
  push:
    branches:
      - main  # Chạy khi có commit push lên nhánh main
  workflow_dispatch:  # Cho phép trigger thủ công

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to VPS (SSH)
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Chuyển đến thư mục backend (api) trên VPS
          cd /opt/ksms/api

          # Kéo mã nguồn mới nhất từ GitHub
          git pull origin main

          # Cài đặt dependencies
          dotnet restore

          # Build API
          dotnet publish -c Release -o /opt/ksms/publish-api

          # Kiểm tra và khởi động lại dịch vụ Docker (nếu sử dụng Docker Compose)
          if [ -f /opt/ksms/docker-compose.yml ]; then
              docker-compose -f /opt/ksms/docker-compose.yml up -d
          else
              echo "docker-compose.yml không tìm thấy, bỏ qua khởi động lại container Docker"
          fi
