name: Deploy Backend

on:
  push:
    branches:
      - main  # Chạy khi có commit push lên nhánh main
  workflow_dispatch:  # Cho phép trigger thủ công

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to VPS (SSH)
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Chuyển đến thư mục của dự án
          cd /path/to/backend

          # Kéo mã nguồn mới nhất từ Git
          git pull origin main

          # Cài đặt dependencies nếu cần (ví dụ: dotnet restore cho .NET)
          dotnet restore

          # Build API
          dotnet publish -c Release -o /app/publish-api

          # Restart service (hoặc chạy Docker container)
          docker-compose -f /path/to/docker-compose.yml up -d
